### ISSUE TITLE
Remove Join Now from the navbar and show user Profile 

### ISSUE THREAD

**Issue by jaswinder6991** [NEARBuilders/gateway#117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Megha-Dev-19** [comment]
@jaswinder6991 I can take it

**Comment by itexpert120** [comment]
In develop branch, the Join Now button redirects to /login page if user is not logged in
If they are logged in and not a member, they go to /join page
else the user dropdown is shown
