### ISSUE TITLE
docs.near.org/bos returning "Page Not Found"

### ISSUE THREAD

**Issue by dawnkelly09** [NEARBuilders/gateway#118]
**Describe the bug**
When attempting to navigate to the docs.near.org/bos documents page, a Page Not Found error is returned. 

**To Reproduce**
1. Go to 'https://docs.near.org/bos' (or click the Docs button from nearbuilders homepage)

**Expected behavior**
To display the BOS docs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MBP
 - Browser Chrome

**Comment by itexpert120** [comment]
Not a NEAR Builders issue. The issue is from near.org side.
