### ISSUE TITLE
Multi-chain ecosystem new line

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#12]
Currently looks like:

<img width="754" alt="Screenshot 2023-11-28 at 9 28 18 AM" src="https://github.com/NEARBuilders/gateway/assets/16282460/b5b0f013-bbe9-4d34-ae43-4687d1a9b59a">

Should be [Figma](https://www.figma.com/file/YxjgMO6YlW8wvK6obiQgfU/Build-DAO?node-id=1401%3A134&mode=dev):

<img width="687" alt="Screenshot 2023-11-28 at 9 29 04 AM" src="https://github.com/NEARBuilders/gateway/assets/16282460/4e9ad701-17ba-4431-8535-1ea5deef1245">

Same for 

<img width="424" alt="Screenshot 2023-11-28 at 9 29 22 AM" src="https://github.com/NEARBuilders/gateway/assets/16282460/4b2d3336-b55e-4d54-a805-cfb624ec19bd">

**Comment by itexpert120** [comment]
Fixed in https://github.com/NEARBuilders/gateway/commit/c454d0dd2e7aa445773d46bd1dbd0fbec9689500
