### ISSUE TITLE
All same border in objectives

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#14]
All objectives should have same color border

<img width="1312" alt="Screenshot 2023-12-27 at 1 26 25 PM" src="https://github.com/NEARBuilders/gateway/assets/16282460/b66b2ed6-158a-4628-967c-40e156764e72">

**Comment by itexpert120** [comment]
Fixed in https://github.com/NEARBuilders/gateway/commit/2fadce6ca0565e4f5e776c0075ef3ad60f4583e8
