### ISSUE TITLE
Clean up Compose

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#147]
Our current Compose is just one large file and is prone to breakage.

We should utilize the patterns from [mob.enar/widget/MainPage.N.Compose](https://near.social/mob.near/widget/WidgetSource?src=mob.near/widget/MainPage.N.Compose) and [mob.near/widget/MainPage.N.Compose.Common](https://near.social/mob.near/widget/WidgetSource?src=mob.near/widget/MainPage.N.Common.Compose). Notice how this Common "wrapper" is able to take in a custom markdown editor from props, and then passes these functionalities to it.

For context, the goal is that we can use these features in whatever editor we plan to swap it out for. The implementation should be style agnostic.

Bonus: we can also adopt the advanced vs plain textbox editor pattern in common compose as well.

**Comment by elliotBraem** [comment]
@itexpert120 it looks like we did lose account id autocomplete w/ apply on click. What I mean by this, is that when you do auto complete and click the account it should autocomplete the text in the compose. Right now if you click it, nothing happens.

Also, we should make sure that the compose clears after posting (post with #test); there was a Toast that had been put in last week, now removed

**Comment by itexpert120** [comment]
I think the autocomplete can be attributed to iframe issue. And I'll implement rest of these features too.

**Comment by itexpert120** [comment]
Fixed, please check new PR
