### ISSUE TITLE
Events Feed: Recurring events capability

### ISSUE THREAD

**Issue by dawnkelly09** [NEARBuilders/gateway#156]
**Is your feature request related to a problem? Please describe.**
I'm starting to use the Events feed to share events with members and it would be really helpful if I could add recurring/repeating events like the daily hang out call without having to do it on each individual day. 

**Describe the solution you'd like**
I would love an option like on Google Calendar where you can indicate the event is repeating and set the frequency and number of repeats when creating or editing the event in question

**Describe alternatives you've considered**
I currently use Google calendar for repeating events but I'd rather get them on the Events feed

**Comment by Megha-Dev-19** [comment]
Hey @dawnkelly09, that's actually a great suggestion, I will get working on this
