### ISSUE TITLE
Do not show "Join now" button if already member, council, or currently proposed

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#16]
We display the join button in three places on the site:

1. Navbar, top right
2. Homepage, "how to join"
3. Homepage, CTA (end of page)

The button in the navbar should not show "Join now" if the logged in user is already a member, part of council, or is currently proposing, it should instead show the profile.

The two buttons on the homepage route to the JoinPage, where it shows the step depending on the following criteria:

```javascript
// get DAO policy, deposit, and group
const policy = Near.view(daoId, "get_policy");

if (policy === null) {
  return "";
}

const deposit = policy.proposal_bond;
const roleId = "community";
const group = policy.roles
  .filter((role) => role.name === roleId)
  .map((role) => role.kind.Group);

const proposalId = Near.view(daoId, "get_last_proposal_id") - 1;

// get data from last proposal
const proposal = Near.view(daoId, "get_proposal", {
  id: proposalId,
});

if (proposal === null) {
  return "";
}

// check if the potential member submitted last proposal
const canJoin = accountId && accountId !== proposal.proposer;
```

**Comment by elliotBraem** [comment]
In this screenshot:

<img width="792" alt="Screenshot 2024-01-03 at 12 22 27 AM" src="https://github.com/NEARBuilders/gateway/assets/16282460/b7aca80c-0e69-4d85-a087-f2a0a6fb048d">

I am not logged in, but I want to be prompted to login

**Comment by itexpert120** [comment]
After joining, the join now button only shows in home page in the join section. Should I hide it from there too?

**Comment by flowscience** [comment]
Related: typo on the confirmation page "View Activiy" should be "View Activity"
![image](https://github.com/NEARBuilders/gateway/assets/10070465/303fcb15-a2a6-46a9-8da0-e7664603712a)

**Comment by itexpert120** [comment]
> Related: typo on the confirmation page "View Activiy" should be "View Activity" ![image](https://private-user-images.githubusercontent.com/10070465/294597246-303fcb15-a2a6-46a9-8da0-e7664603712a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTIyNzUsIm5iZiI6MTcwNDQ5MTk3NSwicGF0aCI6Ii8xMDA3MDQ2NS8yOTQ1OTcyNDYtMzAzZmNiMTUtYTJhNi00NmE5LThkYTAtZTc2NjQ2MDM3MTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIxNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNjE5MGQ0NWEzNDA4MzVlMzBmYWUxODMzNDdmNTIyYTE5MzMzZmIzOWNhMTQ5NDI2MGVjOTU1MDc4YTUxYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.127pWY_BE7jlEbnj-Jz1FEToI4aOcuzls-8ZYFaJgqc)

Fixed

**Comment by RamboGj** [comment]
Please review this PR
https://github.com/NEARBuilders/gateway/pull/26

**Comment by RamboGj** [comment]
@Megha-Dev-19
-  What is your role?
- Are you running it locally?

I can't reproduce it on my side neither in prod or dev

**Comment by Megha-Dev-19** [comment]
I'm running it on prod, I m member of `community`. 
<img width="1226" alt="image" src="https://github.com/NEARBuilders/gateway/assets/100185149/05ca9c87-43ff-498a-9c5c-4f8a573d7481">

**Comment by RamboGj** [comment]
@Megha-Dev-19 just checked it.

From my knowledge related to this PR, the Join now buttons on homepage should keep showing "Join now" so users can easily access the **/join** page and check their current status.
Maybe I misgot something, but I believe it's working as expected

**Comment by Megha-Dev-19** [comment]
oh I see, I believe we should not show "Join Now", either completely hide it or show the status
because it actually confused me.
@RamboGj thanks for clarifying

**Comment by itexpert120** [comment]
No that is incorrect, if someone has already joined, then they should only see the user dropdown instead of "Join Now" button.

Here is how the flow is supposed to be:

Show Sign in button if the user has not signed in. This takes them to either the login page or open the login modal.
If someone has signed in and they have not joined, the Join Now button should show and take them to the join page.
If someone has signed in and they have joined, then the user dropdown should be shown so they can logout or switch to another account or do something else.

I hope that clears that up.
________________________________

**Comment by Megha-Dev-19** [comment]
@itexpert120 that's for the topbar, what about the other sections where we have "join now"
eg: 
<img width="1451" alt="image" src="https://github.com/NEARBuilders/gateway/assets/100185149/5e2bf4aa-7367-4626-8e86-15ec50b47a6b">
<img width="1512" alt="image" src="https://github.com/NEARBuilders/gateway/assets/100185149/33caf9bf-287a-4eb9-88f6-e9a88cfa7c4a">

**Comment by RamboGj** [comment]
@itexpert120  I don't think the user dropdown is supposed to be used on other section than the navbar

**Comment by itexpert120** [comment]
My mistake. I thought you guys were talking about navbar.

For the home page sections, I think changing the Join now button to "Already Joined" or "Pending Approval" makes sense?
