### ISSUE TITLE
Option to "view source"

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#160]
We want to add a "View Source" and "Fork" buttons to the Build DAO gateway, just like Near.social has:

<img width="482" alt="Screenshot 2024-02-15 at 10 43 34 AM" src="https://github.com/NEARBuilders/gateway/assets/16282460/c967f048-112e-494f-82ab-260c741be04b">

On click, it should show the source of the page in the content. Or it should link to "/edit/:path" to bring up the editor

**Comment by itexpert120** [comment]
Our gateway has everything routed from buildhub.near/widget/app?

**Comment by elliotBraem** [comment]
@itexpert120 

Yes, but this can still work. See [this](https://everything.dev/?page=build) -- you had "view source" implemented when you first did the transition/refactor.

When view source is selected, it takes the current route and passes it to WidgetSrc
