### ISSUE TITLE
Draft should be specific to post type

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#18]
Currently we are able to update posts and save to local storage, but the value is overriding the templates. The draft should be unique to the feed type selected, and the feed type should show the correct template at first load.

For example notice how even though I am toggling post type which should change template, it is still showing the same draft and template:

<img width="887" alt="Screenshot 2024-01-03 at 1 26 25 AM" src="https://github.com/NEARBuilders/gateway/assets/16282460/c8612d84-5cf7-4ad2-8c65-1bbafd9f4dc0">

<img width="986" alt="Screenshot 2024-01-03 at 1 26 10 AM" src="https://github.com/NEARBuilders/gateway/assets/16282460/a2fcf81b-e1d4-4c7c-a480-1b9050a4e1db">

A page should load with the draft specific to the feed key, this can be managed with Storage API, privateGet and privateSet: 
https://docs.near.org/bos/api/storage

Basic example for one compose, but no template: https://near.social/mob.near/widget/WidgetSource?src=mob.near/widget/MainPage.N.Compose

**Comment by itexpert120** [comment]
Fixed in https://github.com/NEARBuilders/gateway/commit/e507a51923afb06de7dd96fe6e45fe885aeb0c3a
