### ISSUE TITLE
Can't update my profile on nearbuilders.org

### ISSUE THREAD

**Issue by bb-face** [NEARBuilders/gateway#214]
**Describe the bug**
When I open the profile page on nearbuilders.org I can only see a blackscreen (and the header)

**To Reproduce**
Go to the [near builders homepage](https://www.nearbuilders.org/), open the dropdown menu by clicking on your profile name (top-right corner of the screen), click on "My profile"

**Expected behavior**
I expect to be able to update information like profile picture and name.

**Screenshots**
<img width="1771" alt="image" src="https://github.com/NEARBuilders/gateway/assets/152608874/03af0b1b-1088-4f33-975b-c707292adfa3">

**Desktop (please complete the following information):**

- OS: Sonoma 14.3.1
- Browser: Chrome
- Version [e.g. 22]: 122

**Comment by elliotBraem** [comment]
I've noticed this for new accounts as well. If an account has not customized its /profile (a new account), then the profile page will not appear.

Even in this situation, we should allow the ability to customize the profile.

**Comment by elliotBraem** [comment]
WArning for no profile

If === context.accountId, edit profile
