### ISSUE TITLE
Links does not show well in markdown

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#22]
![Screenshot 2024-01-04 at 9 36 45 PM](https://github.com/NEARBuilders/gateway/assets/16282460/22e8e835-62fa-4fcc-b79f-d0e3b0757ec1)

I think it should be bold white, underlined?

**Comment by elliotBraem** [comment]
Or blue. This only happens in preview apparently

<img width="949" alt="Screenshot 2024-01-04 at 11 42 59 PM" src="https://github.com/NEARBuilders/gateway/assets/16282460/cc2a62b7-90e3-4848-a2e4-a984895d694d">

**Comment by HimanshuDTU18** [comment]
can you assign this to me?

**Comment by itexpert120** [comment]
The links are Blue in component library

**Comment by elliotBraem** [comment]
@itexpert120 is the library post component being used for the preview in Compose? 

@HimanshuDTU18 you're free to pick it up as well; make the change, create a PR, and make sure to record hours

**Comment by itexpert120** [comment]
should I replace the preview with post component?

**Comment by elliotBraem** [comment]
Yes
