### ISSUE TITLE
Edit Posts: Should generate existing post text in modal

### ISSUE THREAD

**Issue by dawnkelly09** [NEARBuilders/gateway#240]
**Describe the bug**
When using "Edit Post" to attempt to edit one of my Feed posts, I noticed it doesn't display the current version of the post text when the modal opens. To use the feature, a user would need to either copy the message, click the Edit button, then paste the old message and make changes, or would need to write an entirely new message. 

**To Reproduce**

1. Go to 'Feed', select one of your posts
2. Click on 'Edit post'
3. See the empty modal

**Expected behavior**
Users expect this modal to contain the current version of their message and to simply make their edits and re-save the post to populate changes

**Screenshots**
![Screenshot 2024-04-10 at 11 29 51 AM](https://github.com/NEARBuilders/gateway/assets/83190195/9cec3a58-ad64-4e2d-841a-b23f234a968b)

**Desktop (please complete the following information):**

- OS: iOS
- Browser Chrome
- Version no idea

**Additional context**
Keep being awesome! :-)

**Comment by Megha-Dev-19** [comment]
I believe it worked before, I once used it and the editor had my post, gotta check the commits.

**Comment by Megha-Dev-19** [comment]
hey @dawnkelly09 it seems to be working now, could you try it once when you have time and let me know if there is still some issue

https://github.com/NEARBuilders/gateway/assets/100185149/1a5fd91d-6d8c-453d-a61b-59d033197ce2

**Comment by dawnkelly09** [comment]
@Megha-Dev-19 confirming this does appear to be working correctly. I will close this issue.
