### ISSUE TITLE
Propose: UI stuck partway through process

### ISSUE THREAD

**Issue by dawnkelly09** [NEARBuilders/gateway#244]
**Describe the bug**
I just tried to use the Propose that comes up when you click the three dots in the upper right of a post and I think it may be broken, at least the UI isn't indicating the process was completed successfully, etc.  

**To Reproduce**

1. I made a Request post: https://near.social/mob.near/widget/MainPage.N.Post.Page?accountId=dawnkelly.near&blockHeight=116614755
2. Clicked the three dots in upper right corner of the post and selected Propose
3. The proposal modal popped up, I selected Text for my Proposal Type and the embed for my post was auto-populated (see screenshot below)
4. I clicked Next, the modal popped up showing the SocialDB data object to be saved and buttons to Confirm or Cancel, I selected Confirm and signed the wallet transaction
5. When the wallet transaction is finished, I'm taken back to the Propose modal with no indication of whether or not things succeeded. My only two options are to close the Propose modal or hit Next which repeats the saving of the same data. 

**Expected behavior**
Everything is good through step 4 where you save data and sign the transaction in the wallet. Works great. 

I would expect the wallet transaction to finish and then get some indication from the UI that the proposal was submitted successfully. This could look like a pop-up/toast with a message or a redirect to the Proposals feed where I would see my Proposal at/near the top of the list as one of the newest submissions. 

**Screenshots**
![Propose](https://github.com/NEARBuilders/gateway/assets/83190195/f8ef947f-530f-49a8-8f7d-ad29f118a713)

**Desktop (please complete the following information):**

- OS: iOS
- Browser Chrome
- Version 

**Additional context**
The proposals were submitted successfully on-chain. 
Transaction hashes:
https://nearblocks.io/txns/9LkhvMoWcTwnBvDD3smCaGyDsqmhFDNjLM9BRfSAXjrz
https://nearblocks.io/txns/B2EYdMArSu4JUr6LXPbRcXYmLqkxyhXSpFRZFKP5r4EC

I was not able to see them on the Proposal Feed earlier. I can't confirm if that is still the case as the Proposal widget seems to be down or being worked on right now.

**Comment by Megha-Dev-19** [comment]
hey @elliotBraem @dawnkelly09
Dawn your point is valid but I m not sure how we can solve this, because Near.call doesn't return promise so I can't know when the proposal is made, and since it's a deposit call we can't use the cache invalidation too.
My suggestion is:
- Once the user clicks on "Create" to create the proposal, we can display a note letting them know where they can find their proposal on gateway, like a link, and then once the user confirm/copy it, we can close the modal and they can approve the txn.
I m open for feedback

**Comment by dawnkelly09** [comment]
Ah, that does make it tricky. As a user, a modal telling me where to check on the proposal would be nice. Then I can copy the url and click a "Dismiss" or similar button to close the modal and return to the Request feed.
