### ISSUE TITLE
Join Now transaction is not updating roles => community => kind => Group account ids from `get_policy` method

### ISSUE THREAD

**Issue by RamboGj** [NEARBuilders/gateway#27]
When I click on join now and sign transaction, everything goes well but it looks like that community account ids array is not being updated. I signed as **rambo-dev.near**, but it is not listed on the _get_policy_ method from [build.sputnik-dao.near contract](https://nearblocks.io/address/build.sputnik-dao.near)

This is an example return from this object path
const policies = Near.view("build.sputnik-dao.near ", "get_policy")

policies => roles => community => kind => group
```
[
'a_liutiev.near', 'escobarindo.near', 'devs.near', 'discodev.near', 'abbakaka.near', 'mintlu.near', 'ndcplug.near', 'jgodwill.near', 'cuongdcdev.near', 'joannaorlova.near', 'efiz.near', 'pivortex.near', 'gdsninjaa.near', 'web3hedge.near', 'lord1.near', 'divgun.near', 'chaotictempest.near', 'chloe.near', 'kuhaku.near', 'manzanal.near', 'megha19.near', 'vlad.near', 'aaron.near', 'achraf.near', 'lukasky.near', 'rektdegen.near', 'chluff.near', 'nearjordan.near', 'whendacha.near', 'bpolania.near', 'mattb.near', 'josecouto.near', 'c74edb82759f476010ce8363e6be15fcb3cfebf9be6320d6cdc3588f1a5b4c0e', 'lennczar.near', 'frado.near', 'nhatcuong224267.near', 'salikc9.near', 'roshaan.near', 'cryptois.near', 'futurevisions.near', 'fiatisabubble.near', 'multi.near', 'itexpert120-contra.near', 'cameron.near', 'flowscience.near', 'aliaksandrh.near', 'root.benjiman.near', 'seth.near', 'bearmans.near
']
```

[Transaction on Explorer](https://nearblocks.io/txns/Ce85TtDgsyDcMuEMnAykFDAZg2KUoANK8sCjDJ223e2F)

**Comment by Megha-Dev-19** [comment]
Hey @RamboGj 
It’s not a bug, you created a proposal to join the community, it will be added after it’s approved.
You can checkout all the proposals [here](https://near.org/astraplusplus.ndctools.near/widget/home?tab=proposals&daoId=build.sputnik-dao.near&page=dao)

**Comment by elliotBraem** [comment]
@RamboGj Yes, as @Megha-Dev-19 said: after clicking Join Now, it creates a proposal to the DAO (build.sputnik-dao.near) to add your account (rambo-dev.near) -- but you are not yet in any role until the proposal is approved.

But it does acknowledge one issue:
When you are logged in, but not a member of the DAO -- how can we determine if you have a pending proposal? 

I think sputnik DAO contract may not be the best dataset to query and check if name exists in list -- this would be much easier using an existing indexer
