### ISSUE TITLE
Consolidate components, reuse templates

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#28]
The resources and feed pages share the same structure:

![image](https://github.com/NEARBuilders/gateway/assets/16282460/751e9b45-2e06-42b0-8587-42e0b63759e0)

However, we currently have quite a few components to do this, rather than reusing them:

Resources.jsx
resources-aside.jsx
Aside.jsx

Feed, Post, and Compose are all part of content (but the routes for the /feeds Aside are coming from Feed, this isn't modular!)

## Acceptance Criteria
- [ ] There is a common widget w/ the Aside + Content layout, neither Aside or Content are specific to any page (completely generic)
- [ ] There is a page specific widget w/ object defined that passes to the common widget for rendering

This is just an idea, but maybe we have:

```
pages/
    Resources -> a widget that defines the resources routes and passes to common buildhub.near/widget/app widget
    Feed -> a widget that defines the feeds and passes to common buildhub.near/widget/app widget
```

## Notes

I've been treating this reusable structure as an "app" on everything.dev, as you can see in [every.near/widget/app](https://near.social/mob.near/widget/WidgetSource?src=every.near/widget/app).

A next step may be how the gateway itself could reuse the same /app widget...  (but let's do this simple implementation first)

![image](https://github.com/NEARBuilders/gateway/assets/16282460/a0046687-82f3-4f2a-b684-6a410eb95d9c)

**Comment by Megha-Dev-19** [comment]
I can work on this, it will give me get better understanding of this repo as well.
