### ISSUE TITLE
Implement Test Button in Nav Bar

### ISSUE THREAD

**Issue by superxgen** [NEARBuilders/gateway#289]
Site update is nearly ready, and we'd like to begin testing. 

To support this, and future tests, we'd be benefitted by a button in our navigation that leads to our development branch. 
![new_nav](https://github.com/NEARBuilders/gateway/assets/107756079/c72a5f47-150b-4234-9d5a-6857fd71282e)

Suggesting we add that now, as implied in this figma draft, and deploy our updates to this branch for testing.
https://www.figma.com/file/O9VBPoKQH80YLndvcbj3Zf/%5BMVP%5D-HomePage-2.0?type=design&node-id=122%3A30146&mode=design&t=6qiYQt6hvMCH86Rj-1

implementing the test button in the nav bar to lead to our development branch (https://test.nearbuilders.org) will accelerate our testing and update cycle, and open up the process to a broader team/community.

**Comment by Megha-Dev-19** [comment]
Just a thought:
May be we should also have an option on develop to shift between testnet and mainnet
like potlock wouldn't work on `testnet`, afaik it only have mainnet staging and production account.
