### ISSUE TITLE
Bookmark posts

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#30]
I want the ability to bookmark a post and to view my bookmarked posts.

- [x] I can bookmark a post
- [x] I can see number of bookmarks on a post (just like a "like")
- [x] I can view a feed of posts I have bookmarked
- [x] I can unbookmark a post

[FIGMA](https://www.figma.com/file/YxjgMO6YlW8wvK6obiQgfU/Build-DAO?node-id=1401%3A134&mode=dev)

**Comment by RamboGj** [comment]
Which smart contract is handling with Bookmarks states?
I can work on it.

**Comment by elliotBraem** [comment]
Love the ambition @RamboGj, but @itexpert120 has already been working on it and this story is just for him to make his pull request against / assert acceptance criteria, sorry that wasn't clear

You should check out the implementation when he is done; bookmarks are similar to [Stars](https://near.social/mob.near/widget/N.StarButton) on near.social
