### ISSUE TITLE
Create reusable layout -> Sidebar, Navbar, Content

### ISSUE THREAD

**Issue by Megha-Dev-19** [NEARBuilders/gateway#306]
![Image](https://github.com/NEARBuilders/gateway/assets/100185149/f42d0f2c-ff18-4ec1-8958-71f431aa86b0)

**Comment by elliotBraem** [comment]
We have layouts for these, `devs.near/widget/Layout` with variants "split", "sidebar", and "standard"

See [demo](https://near.social/devs.near/widget/Layout.demo)
