### ISSUE TITLE
[Feedback] Create Project Flow -> Select field mismatch

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#347]
On brave browser, team size <select does not match the style of other fields (let's make sure this comes from our component library, too)

<img width="389" alt="Screenshot 2024-06-04 at 11 36 43 PM" src="https://github.com/NEARBuilders/gateway/assets/16282460/1e8943d3-f874-4171-9a60-285ecc2db01c">

**Comment by itexpert120** [comment]
![image](https://github.com/NEARBuilders/gateway/assets/46527178/6ec73f2b-02cd-445f-93c2-95df59724f57)
Fixed on develop
