### ISSUE TITLE
[Feedback] Create Project Flow -> Tags should follow standard

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#352]
It seems that tags are not following the metadata standard, and are instead being saved as a stringified array.

This should be converted to use the standard, which is an object with keys:

[Standard](https://github.com/NearSocial/standards/blob/main/types/common/Tags.md)

![Screenshot 2024-06-04 at 11 53 48 PM](https://github.com/NEARBuilders/gateway/assets/16282460/c194242d-a718-4498-8ce4-493157689d55)

**Comment by Megha-Dev-19** [comment]
oh yes, thanks for noticing, will update it.
