### ISSUE TITLE
Project page !== Projects page

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#355]
When on page=projects and navigating to a project page, it seems to navigate the full page with a new sidebar.

Instead, only the content should change.

![image](https://github.com/NEARBuilders/gateway/assets/16282460/ae2508b5-0c07-4288-b6fa-c17fc17582ab)

When navigating to page=project, I would expect to only see project page with no navbar

![Screenshot 2024-06-05 at 12 11 32 AM](https://github.com/NEARBuilders/gateway/assets/16282460/d1c4e0dd-c474-443e-9791-a3e423d3c44b)

**Comment by itexpert120** [comment]
Need more clarification on this. Meeting @elliotBraem?

**Comment by Megha-Dev-19** [comment]
Let's show the quick snapshot of project when user selects any project. 
here is the [design](https://www.figma.com/design/ZVfCNEHuD7tZKFmod3pjnh/Build-DAO---UX%2FUI-Design?node-id=3471-197566&t=eLyPo45wPWXMD6CG-4)
cc: @elliotBraem @itexpert120
