### ISSUE TITLE
Search doesn't work on import project from Potlock

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#393]
https://www.nearbuilders.org/builddao.near/widget/Index?page=projects&tab=potlockImport

Typing in the search bar has no changes

**Comment by Megha-Dev-19** [comment]
@elliotBraem, the user has to use "Enter" to search it, maybe we should add a button, rather than doing search onChange to optimise search.

https://github.com/NEARBuilders/gateway/assets/100185149/0b097210-e6f6-4591-a7ad-1b76d0ec62f2
