### ISSUE TITLE
Display posts in the feed below the editor on the Feeds page.

### ISSUE THREAD

**Issue by jaswinder6991** [NEARBuilders/gateway#41]
**Is your feature request related to a problem? Please describe.**
Currently if you visit the https://www.nearbuilders.org/feed in any of the categories, you can only see the Create component to let people post of that particular type. We want to display posts of that category right below the Create component.

**Describe the solution you'd like**
We want the post feed filtered by that particular category to be displayed below the Create widget. You can filter the global feed using the appropriate hashtag.

**Design**
[Figma](https://www.figma.com/file/YxjgMO6YlW8wvK6obiQgfU/Build-DAO?type=design&node-id=1869-62&mode=design&t=NDnIpjC911S2Jucy-4 )

**Comment by Megha-Dev-19** [comment]
I can take it
