### ISSUE TITLE
Tags overflow on project card

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#414]
![Screenshot 2024-06-18 at 11 07 07 AM](https://github.com/NEARBuilders/gateway/assets/16282460/d7646e5f-26ef-4cca-ad49-ac684a1ba91f)

![Screenshot 2024-06-18 at 11 26 16 AM](https://github.com/NEARBuilders/gateway/assets/16282460/d506cff9-6d79-401d-8974-88d1921e14f6)

## Acceptance Criteria
- [ ] No overflow on both Grid + List cards

**Comment by itexpert120** [comment]
How do you want it to be handled? Should they be truncated or there should be scroll bar?

**Comment by Megha-Dev-19** [comment]
hey @itexpert120, I think we can wrap it, it good to display all the tags, since it vital information of the project, and we also use them in filters.

**Comment by itexpert120** [comment]
How do we wrap this in the list view?

**Comment by Megha-Dev-19** [comment]
> How do we wrap this in the list view?

You can add a max-width within which it will wrap, or may be ask Cecilia for a design, she might have better ideas about how to handle it.

**Comment by itexpert120** [comment]
That sounds like a plan, I'll ask her
