### ISSUE TITLE
Improve Compose - Drafts (2): Save Draft

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#57]
## Overview

As a user, I want to save my post drafts, so I can write multiple at the same time.

[FIGMA](https://www.figma.com/file/YxjgMO6YlW8wvK6obiQgfU/Build-DAO?type=design&node-id=2307-1024&mode=dev)
![Image](https://github.com/NEARBuilders/gateway/assets/16282460/16bb1d26-b048-49ba-98da-9c46c90358a3)

## Acceptance Criteria
- [ ] There is a new "Save Draft" button that appears above the text editor
- [ ] When I click the "Save Draft" button, my draft should be saved to the [Storage API](https://docs.near.org/bos/api/storage).
- [ ] My draft should be visible in the Drafts Modal #58  (Clicking it does nothing, see next issue #59 )

**Comment by itexpert120** [comment]
merged in another branch
