### ISSUE TITLE
Improve Compose - Drafts (1): Draft Modal

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#58]
## Overview

As a user, I want to continue existing drafts

![Image](https://github.com/NEARBuilders/gateway/assets/16282460/6810259e-dd6e-4b16-a4d0-8a0e311adc40)

Modal:
![Image](https://github.com/NEARBuilders/gateway/assets/16282460/c7c62eec-ccc6-4670-a696-1bfb0694175b)

## Acceptance Criteria
- [ ] There is a new "Continue Drafts" button that appears above the Compose
- [ ] When I click the "Continue Drafts" button, a modal appears (#56) to view drafts.
- [ ] When I click back in the top left, the modal closes.

**Comment by itexpert120** [comment]
merged in another branch
