### ISSUE TITLE
Improve Compose - Drafts (3): Select Draft

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#59]
## Overview

As a user, I want to apply an existing draft, so I can continue writing.

![Image](https://github.com/NEARBuilders/gateway/assets/16282460/c7c62eec-ccc6-4670-a696-1bfb0694175b)

## Acceptance Criteria
- [ ] From the Draft modal, existing drafts should appear
- [ ] When I click an existing draft, the modal should close and the draft should populate the compose

**Comment by itexpert120** [comment]
merged in another branch
