### ISSUE TITLE
Fix padding from top

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#6]
The grid/top landing section seems smaller than it should be. I think it's because of not compensating padding away from the top navigation?

![Image](https://github.com/NEARBuilders/gateway/assets/16282460/7410324d-7030-4296-bada-9fcfcbe2e59a)

**Comment by itexpert120** [comment]
<img width="488" alt="image" src="https://github.com/NEARBuilders/gateway/assets/46527178/c0d7d147-159d-4dd2-9960-8b2df6ba9cf3">
It is same, idk why it looks like that
