### ISSUE TITLE
Improve Compose: AccountId Autocomplete & Attach Image

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#61]
## Overview

Our current Compose component is missing some important features: AccountId Autocomplete and the ability to Attach an Image.

If you view the Compose on [near.social](https://near.social) ([mob.near/widget/MainPage.N.Compose](https://near.social/#/mob.near/widget/MainPage.N.Compose)), you will notice these features: When you type @, a autocomplete appears below the compose. When you click image, you can upload an image to IPFS and attach it.

## Acceptance Criteria
- [ ] Typing @ brings up an autocomplete for accountId
- [ ] Selecting an accountId from autocomplete completes it in the text editor
- [ ] When you click attach image, attach file comes up, uploads to IPFS, and attaches to content
- [ ] Solution is **style agnostic** and flexible for other types of editors. Can be reused by other projects that implement a text editor. (such as https://github.com/nearbuilders/create)

## Implementation
I strongly advise that we utilize the patterns from [mob.near/widget/MainPage.N.Compose.Common](https://near.social/mob.near/widget/WidgetSource?src=mob.near/widget/MainPage.N.Common.Compose). Notice how this Common "wrapper" is able to take in a custom markdown editor from props, and then passes these functionalities to it. 
Feel free to fork this pattern.

For context, the goal is that we can use these features in whatever editor we plan to swap it out for. The implementation should be **style agnostic**.

Bonus: we can also adopt the advanced vs plain textbox editor pattern in common compose as well.

**Comment by Megha-Dev-19** [comment]
I can take this
