### ISSUE TITLE
After successful post, compose should disappear

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/gateway#78]
Users will occasionally create duplicate posts, this likely because there is no confirmation

![telegram-cloud-photo-size-4-5825429182434360779-y](https://github.com/NEARBuilders/gateway/assets/16282460/20cf5354-b850-4e5c-9a2f-f5b5407fdab6)

"When I post and it's successful..  The post resolution widget should disappear.. Else users will think it's not yet successful.. And will be clicking multiple times"

After posting successfully (onCommit), the compose should reset. What else should happen?

Take inspiration from near.social and near.org posting strategies

**Comment by itexpert120** [comment]
I have already completed this in another PR. I will move into new PR.
