### ISSUE TITLE
Create "First time login" component for new users

### ISSUE THREAD

**Issue by jaswinder6991** [NEARBuilders/gateway#84]
**Problem**
Currently, when a new user logs in they are redirected to the feed page. Here they are exposed to different projects and ongoing activities. As a new user, it is difficult to navigate as to what can they do immediately or what their first step should be.

**Solution**
We want to implement a first time login component, that works as starting guide of sorts for the new users. Here we create a 3 step process to get involved easily with BuildDAO. (Cana extend this flow later.)
1. Follow BuildDAO account for updates.
2. Recommend builders you might want to follow.
3. Create an introduction post. 

**Figma**
- [Follow BuildDAO account.](https://www.figma.com/file/ZVfCNEHuD7tZKFmod3pjnh/Build-DAO?type=design&node-id=133-2120&mode=design&t=2PsTxgMmMtzema1w-4)
- [Recommend builders.](https://www.figma.com/file/ZVfCNEHuD7tZKFmod3pjnh/Build-DAO?type=design&node-id=133-2145&mode=design&t=2PsTxgMmMtzema1w-4) 
- [Introduction post.](https://www.figma.com/file/ZVfCNEHuD7tZKFmod3pjnh/Build-DAO?type=design&node-id=133-2164&mode=design&t=2PsTxgMmMtzema1w-4)

**Acceptance criteria**
- [ ] The component should only be displayed if the user has logged in for the first time. 
- [ ] User should be able to skip a step.

**Comment by Megha-Dev-19** [comment]
Hey Jas, I can pick it
