### ISSUE TITLE
Identify first time login on the Build DAO gateway

### ISSUE THREAD

**Issue by jaswinder6991** [NEARBuilders/gateway#85]
To create custom onboarding experience for new users, we want to identify if the user has logged in for the first time. 
In this story we want to capture different ways we can identify this:

1. Has the user made a post already using Build DAO gateway. Check their social graph for Build DAO posts. (Example #build, #resolutions etc.)
2. Use a NEAR horizon like Terms of Service modal that stores the information when user logs in the first time. As a part of the onboarding widget, at the end we store this information that the user has seen the onboarding once. Even if they skip it, close it, we store the information. With this, all existing users would see the onboarding widget at least once too. 
3. TBD

**Comment by Megha-Dev-19** [comment]
Hey, may be we can make a post from BuildDao account welcoming them, like we do in telegram general channel when someone joins the group.

**Comment by itexpert120** [comment]
We can use a key like, `hasOnboarded: false` and save it via `Storage.privateSet`. If the key is false, it means they are first time users, and if the key is true, we don't have to show the onboarding widget.
